export type CameraMode = "orbit" | "north";
export type MapLayer = "slab" | "plan" | "walls" | "cores" | "furniture" | "outline" | "shafts";

/** Wall centerline in plan-normalized coordinates (±0.5, +z = plan down). */
export type WallSegment = [x1: number, z1: number, x2: number, z2: number];

export interface BuildingPlan {
  widthPx: number;
  heightPx: number;
}

/** Registered PDF page-space rectangle shared by every floor in one building. */
export interface MasterRect {
  x: number;
  y: number;
  w: number;
  h: number;
}

/** Generated by scripts/floorplan/build.py — do not edit by hand. */
export interface FloorGeometry {
  id: string;
  level: number;
  texture: string;
  walls: WallSegment[];
}

/** Human-curated floor facts (survive asset regeneration). */
export interface FloorMeta {
  id: string;
  label: string;
  title: string;
  rooms: string[];
}

/** Axis on the plan; +z = plan down (south), so "-z" is north. */
export type PlanAxis = "+x" | "-x" | "+z" | "-z";

/** Axis-aligned rect in normalized plan coordinates (±0.5). */
export interface NormRect {
  x0: number;
  z0: number;
  x1: number;
  z1: number;
}

export type VoidKind = "atrium" | "escalator-well" | "stair-well";

export interface VoidFeature {
  rect: NormRect;
  kind: VoidKind;
}

export interface StairFeature {
  id: string;
  rect: NormRect;
  /** Direction of ascent, read from the tread hatching on the plan. */
  up: PlanAxis;
  /**
   * The flight leaves this floor going down instead of arriving from it going
   * up. A deck or bridge whose only slab is its own level still draws the
   * stair that takes you off it; modelled as a climb it would rise into empty
   * air above the deck.
   */
  down?: boolean;
}

export interface EscalatorFeature {
  id: string;
  rect: NormRect;
  up: PlanAxis;
  lanes: number;
}

/** A band of classrooms sharing an x-extent, partitioned along z. */
export interface ClassroomRow {
  x: [number, number];
  rows: [number, number][];
  /** Wall that carries the whiteboard (default "-z" = north). */
  facing: PlanAxis;
}

export type CommonKind = "corridor" | "hall";

/**
 * Invented walkable zone (not a plan symbol): populated with schematic
 * benches/planters/tables so occupied floor reads apart from the voids.
 */
export interface CommonArea {
  rect: NormRect;
  kind: CommonKind;
}

export interface ElevatorShaft {
  id: string;
  rect: NormRect;
  /** Inclusive floor-level span the shaft runs through. */
  levels: [number, number];
}

export interface FloorFeatures {
  voids: VoidFeature[];
  stairs: StairFeature[];
  escalators: EscalatorFeature[];
  classrooms: ClassroomRow[];
  commons: CommonArea[];
}

export interface BuildingFeatures {
  /** Slab outline per floor; floors without an override use `default`. */
  footprints: { default: [number, number][]; byFloor: Record<string, [number, number][]> };
  elevators: ElevatorShaft[];
}

export type BuildingFloor = FloorMeta &
  FloorGeometry & {
    features: FloorFeatures;
  };

export interface BuildingDefinition {
  id: string;
  name: string;
  englishName: string;
  levelsLabel: string;
  plan: BuildingPlan;
  /** The sole source of campus-relative scale and placement. */
  masterRect: MasterRect;
  floors: BuildingFloor[];
  features: BuildingFeatures;
}
